In [ ]:
# Import statements
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,ConfusionMatrixDisplay
from sklearn import naive_bayes
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from bs4 import BeautifulSoup
from nltk.corpus import stopwords
from sklearn.ensemble import RandomForestClassifier

In [ ]:
import pandas as pd
data = pd.read_csv("appl_1_amazon_pc.csv")
data.head()

marketplace  customer_id       review_id  product_id  product_parent  \
0          US     11555559  R1QXC7AHHJBQ3O  B00IKPX4GY         2693241   
1          US     31469372  R175VSRV6ZETOP  B00IKPYKWG         2693241   
2          US     26843895  R2HRFF78MWGY19  B00IKPW0UA         2693241   
3          US     19844868   R8Q39WPKYVSTX  B00LCHSHMS         2693241   
4          US      1189852  R3RL4C8YP2ZCJL  B00IKPZ5V6         2693241   

                           product_title product_category  star_rating  \
0  Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            5   
1  Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            3   
2  Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            5   
3  Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            4   
4  Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            5   

   helpful_votes  total_votes vine verified_purchase  \
0              0            0    N                 Y   
1              0            0    N                 N   
2              0            0    N                 Y   
3              0            0    N                 N   
4              0            0    N                 Y   

                                     review_headline  \
0                                         Five Stars   
1  Lots of ads Slow processing speed Occasionally...   
2                            Well thought out device   
3  Not all apps/games we were looking forward to ...   
4                                         Five Stars   

                                         review_body review_date  sentiment  
0                                      Great love it  2015-08-31          1  
1  Lots of ads<br />Slow processing speed<br />Oc...  2015-08-31          0  
2  Excellent unit.  The versatility of this table...  2015-08-31          1  
3  I bought this on Amazon Prime so I ended up bu...  2015-08-31          1  
4  All Amazon products continue to meet my expect...  2015-08-31          1

In [ ]:
# print various attributes available in the dataset
data.columns

Index(['marketplace', 'customer_id', 'review_id', 'product_id',
       'product_parent', 'product_title', 'product_category', 'star_rating',
       'helpful_votes', 'total_votes', 'vine', 'verified_purchase',
       'review_headline', 'review_body', 'review_date', 'sentiment'],
      dtype='object')

In [ ]:
# print properties of attributes in the dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30846 entries, 0 to 30845
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   marketplace        30846 non-null  object
 1   customer_id        30846 non-null  int64 
 2   review_id          30846 non-null  object
 3   product_id         30846 non-null  object
 4   product_parent     30846 non-null  int64 
 5   product_title      30846 non-null  object
 6   product_category   30846 non-null  object
 7   star_rating        30846 non-null  int64 
 8   helpful_votes      30846 non-null  int64 
 9   total_votes        30846 non-null  int64 
 10  vine               30846 non-null  object
 11  verified_purchase  30846 non-null  object
 12  review_headline    30846 non-null  object
 13  review_body        30846 non-null  object
 14  review_date        30846 non-null  object
 15  sentiment          30846 non-null  int64 
dtypes: int64(6), object(10)
memory usage: 3.

In [ ]:
data['sentiment'] = np.where(data['star_rating'] == 5.0, 1,
                           np.where(data['star_rating'] == 4.0, 1, 0))

In [ ]:
data.head()

marketplace  customer_id       review_id  product_id  product_parent  \
0          US     11555559  R1QXC7AHHJBQ3O  B00IKPX4GY         2693241   
1          US     31469372  R175VSRV6ZETOP  B00IKPYKWG         2693241   
2          US     26843895  R2HRFF78MWGY19  B00IKPW0UA         2693241   
3          US     19844868   R8Q39WPKYVSTX  B00LCHSHMS         2693241   
4          US      1189852  R3RL4C8YP2ZCJL  B00IKPZ5V6         2693241   

                           product_title product_category  star_rating  \
0  Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            5   
1  Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            3   
2  Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            5   
3  Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            4   
4  Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            5   

   helpful_votes  total_votes vine verified_purchase  \
0              0            0    N                 Y   
1              0            0    N                 N   
2              0            0    N                 Y   
3              0            0    N                 N   
4              0            0    N                 Y   

                                     review_headline  \
0                                         Five Stars   
1  Lots of ads Slow processing speed Occasionally...   
2                            Well thought out device   
3  Not all apps/games we were looking forward to ...   
4                                         Five Stars   

                                         review_body review_date  sentiment  
0                                      Great love it  2015-08-31          1  
1  Lots of ads<br />Slow processing speed<br />Oc...  2015-08-31          0  
2  Excellent unit.  The versatility of this table...  2015-08-31          1  
3  I bought this on Amazon Prime so I ended up bu...  2015-08-31          1  
4  All Amazon products continue to meet my expect...  2015-08-31          1

In [ ]:
# get unique values of product title column
data["product_title"].unique()

array(['Fire HD 7, 7" HD Display, Wi-Fi, 8 GB'], dtype=object)

In [ ]:
# choose a particular product for analysis
prod_hosa = data.loc[data["product_title"]=='Fire HD 7, 7" HD Display, Wi-Fi, 8 GB']
prod_hosa

marketplace  customer_id       review_id  product_id  product_parent  \
0              US     11555559  R1QXC7AHHJBQ3O  B00IKPX4GY         2693241   
1              US     31469372  R175VSRV6ZETOP  B00IKPYKWG         2693241   
2              US     26843895  R2HRFF78MWGY19  B00IKPW0UA         2693241   
3              US     19844868   R8Q39WPKYVSTX  B00LCHSHMS         2693241   
4              US      1189852  R3RL4C8YP2ZCJL  B00IKPZ5V6         2693241   
...           ...          ...             ...         ...             ...   
30841          US     44834233  R366C7ARIWLN7R  B00IKPW0UA         2693241   
30842          US     13376158  R35PL0AOCUXLU9  B00IKPYKWG         2693241   
30843          US     40485963  R18ZJVY86AUFII  B00KC6XV58         2693241   
30844          US     33485035  R36QVLQXMCZRSJ  B00IKPYKWG         2693241   
30845          US      7015231  R1MWVQUDBUADGE  B00IKPYKWG         2693241   

                               product_title product_category  star_rating  \
0      Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            5   
1      Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            3   
2      Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            5   
3      Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            4   
4      Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            5   
...                                      ...              ...          ...   
30841  Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            5   
30842  Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            5   
30843  Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            5   
30844  Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            4   
30845  Fire HD 7, 7" HD Display, Wi-Fi, 8 GB               PC            5   

       helpful_votes  total_votes vine verified_purchase  \
0                  0            0    N                 Y   
1                  0            0    N                 N   
2                  0            0    N                 Y   
3                  0            0    N                 N   
4                  0            0    N                 Y   
...              ...          ...  ...               ...   
30841           3720         3875    N                 Y   
30842           2716         2849    N                 Y   
30843           1525         1629    N                 Y   
30844            143          163    N                 Y   
30845              2           10    N                 N   

                                         review_headline  \
0                                             Five Stars   
1      Lots of ads Slow processing speed Occasionally...   
2                                Well thought out device   
3      Not all apps/games we were looking forward to ...   
4                                             Five Stars   
...                                                  ...   
30841  A great upgrade for me from an older Kindle Fire!   
30842                               Great Value for $139   
30843                   Even grandma has it figured out!   
30844                        The Honda Accord of Tablets   
30845                                    won't regret it   

                                             review_body review_date  \
0                                          Great love it  2015-08-31   
1      Lots of ads<br />Slow processing speed<br />Oc...  2015-08-31   
2      Excellent unit.  The versatility of this table...  2015-08-31   
3      I bought this on Amazon Prime so I ended up bu...  2015-08-31   
4      All Amazon products continue to meet my expect...  2015-08-31   
...                                                  ...         ...   
30841  [[VIDEOID:moP3B6GS5RL8LY]]I purchased the orig...  2014-10-03   
30842  I'm writing this review with the benefit of be...  2014-10-03   
30843  I purchased this Kindle for my gran

In [ ]:
# #split data-set to train and test

X = prod_hosa['review_body']
Y = prod_hosa['sentiment']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state=42)

In [ ]:
# function to remove html elements from the reviews
def removeHTML(raw_text):
    clean_HTML = BeautifulSoup(raw_text, 'lxml').get_text()
    return clean_HTML

In [ ]:
# function to remove special characters and numbers from the reviews4961
def removeSpecialChar(raw_text):
    clean_SpecialChar = re.sub("[^a-zA-Z]", " ", raw_text)
    return clean_SpecialChar

In [ ]:
# function to convert all reviews into lower case
def toLowerCase(raw_text):
    clean_LowerCase = raw_text.lower().split()
    return( " ".join(clean_LowerCase))

In [ ]:
# function to remove stop words from the reviews
def removeStopWords(raw_text):
    stops = set(stopwords.words("english"))
    words = [w for w in raw_text if not w in stops]
    return( " ".join(words))

In [ ]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
# X_training clean set
X_train_cleaned = []

for val in X_train:
    val = removeHTML(val)
    val = removeSpecialChar(val)
    val = toLowerCase(val)
    removeStopWords(val)
    X_train_cleaned.append(val)

<ipython-input-73-c0f252bc04f4>:3: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  clean_HTML = BeautifulSoup(raw_text, 'lxml').get_text()


In [ ]:
Y_train

29034    1
4015     1
4101     1
9952     0
7109     1
        ..
29802    1
5390     1
860      1
15795    1
23654    1
Name: sentiment, Length: 24676, dtype: int64

In [ ]:
# Convert a collection of raw documents to a matrix of TF-IDF features. This is required so as to train the model using features instead of
# raw strings.
tvec = TfidfVectorizer(use_idf=True,
strip_accents='ascii')

X_train_tvec = tvec.fit_transform(X_train_cleaned)

In [ ]:
# Support Vector Classifier model
svr_lin = LinearSVC(multi_class='ovr',C=1.0,loss='squared_hinge', dual=False)
svr_lin.fit(X_train_tvec, Y_train)

LinearSVC(dual=False)

In [ ]:
# Predict using training and testing data and display the accuracy, f-1 score, precision for Positive and Negative Sentiment Classifiers
svr_lin_predictions = svr_lin.predict(tvec.transform(X_test_cleaned))
report = classification_report(Y_test,svr_lin_predictions, output_dict=True)
data_report = pd.DataFrame(report).transpose().round(2)
cm = sns.light_palette("yellow", as_cmap=True)
data_report.style.background_gradient(cmap=cm)

In [ ]:

# confusion matrix
svr_lin_predictions=svr_lin.predict(tvec.transform(X_test_cleaned))
cm=confusion_matrix(Y_test,svr_lin_predictions)
cm

array([[ 644,  374],
       [ 191, 4961]])

In [ ]:
# testing the model with sample 'Positive' review
demo_review_2 = np.array(['Excellent product. Works well and performs as expected.'])
demo_review_X_test_2 = tvec.transform(demo_review_2)
print(svr_lin.predict(demo_review_X_test_2))

# expected output = 1 (Positive)
# actual output = 1 (Positive)

[1]


In [ ]:
# Random Forest model
random_forest = RandomForestClassifier()
random_forest.fit(X_train_tvec, Y_train)

RandomForestClassifier()

In [ ]:
# Predict using training and testing data and display the accuracy, f-1 score, precision for Positive and Negative Sentiment Classifiers
ranfrst_predictions = random_forest.predict(tvec.transform(X_test_cleaned))
report = classification_report(Y_test,ranfrst_predictions, output_dict=True)
data_report = pd.DataFrame(report).transpose().round(2)
cm = sns.light_palette("red", as_cmap=True)
data_report.style.background_gradient(cmap=cm)

In [ ]:
# confusion matrix
ranfrst_predictions=random_forest.predict(tvec.transform(X_test_cleaned))

cm=confusion_matrix(Y_test,ranfrst_predictions)
cm

array([[ 297,  721],
       [  63, 5089]])

In [ ]:
# testing the model with sample 'Negative' review
demo_review = np.array(['Do not buy. Fake Product.'])
demo_review_X_test = tvec.transform(demo_review)
print(random_forest.predict(demo_review_X_test))

# expected output = 0 (Negative)
# actual output = 0 (Negative)

[0]


In [ ]:
# testing the model with sample 'Positive' review
demo_review_2 = np.array(['Original Product. Great Performance.'])
demo_review_X_test_2 = tvec.transform(demo_review_2)
print(random_forest.predict(demo_review_X_test_2))

# expected output = 1 (Positive)
# actual output = 1 (Positive)

[1]


In [ ]:
# K-Nearest Neighbor model
knn = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
knn.fit(X_train_tvec, Y_train)

KNeighborsClassifier()

In [ ]:
# Predict using training and testing data and display the accuracy, f-1 score, precision for Positive and Negative Sentiment Classifiers
knn_predictions = knn.predict(tvec.transform(X_test_cleaned))
report = classification_report(Y_test,knn_predictions, output_dict=True)
data_report = pd.DataFrame(report).transpose().round(2)
cm = sns.light_palette("gray", as_cmap=True)
data_report.style.background_gradient(cmap=cm)

In [ ]:
# testing the model with sample 'Negative' review
demo_review = np.array(['Bad product. Very much disappointed'])
demo_review_X_test = tvec.transform(demo_review)
print(knn.predict(demo_review_X_test))

# expected output = 0 (Negative)
# actual output = 0 (Negative)

[0]


In [ ]:
# testing the model with sample 'Positive' review
demo_review_2 = np.array(['Excellent product. Works well and performs as expected.'])
demo_review_X_test_2 = tvec.transform(demo_review_2)
print(knn.predict(demo_review_X_test_2))

# expected output = 1 (Positive)
# actual output = 1 (Positive)

[1]


In [ ]:
# Logistic regression model
lr = LogisticRegression()
lr.fit(X_train_tvec, Y_train)

LogisticRegression()

In [ ]:
# Predict using training and testing data and display the accuracy, f-1 score, precision for Positive and Negative Sentiment Classifiers
lr_predictions = lr.predict(tvec.transform(X_test_cleaned))
report = classification_report(Y_test,lr_predictions, output_dict=True)
data_report = pd.DataFrame(report).transpose().round(2)
cm = sns.light_palette("purple", as_cmap=True)
data_report.style.background_gradient(cmap=cm)

In [ ]:
# confusion matrix
lr_predictions=lr.predict(tvec.transform(X_test_cleaned))

cm=confusion_matrix(Y_test,lr_predictions)
cm

array([[ 601,  417],
       [ 162, 4990]])

In [ ]:
# testing the model with sample 'Negative' review
demo_review = np.array(['Poor quality. Faulty device.'])
demo_review_X_test = tvec.transform(demo_review)
print(lr.predict(demo_review_X_test))

# expected output = 0 (Negative)
# actual output = 0 (Negative)

[0]


In [ ]:
# testing the model with sample 'Positive' review
demo_review_2 = np.array(['Best product.'])
demo_review_X_test_2 = tvec.transform(demo_review_2)
print(lr.predict(demo_review_X_test_2))

# expected output = 1 (Positive)
# actual output = 1 (Positive)

[1]


In [ ]:
# Naive Bayes model
nbm = naive_bayes.MultinomialNB()
nbm.fit(X_train_tvec, Y_train)

MultinomialNB()

In [ ]:
# Predict using training and testing data and display the accuracy, f-1 score, precision for Positive and Negative Sentiment Classifiers
nbm_predictions = nbm.predict(tvec.transform(X_test_cleaned))
report = classification_report(Y_test,nbm_predictions, output_dict=True)
data_report = pd.DataFrame(report).transpose().round(2)
cm = sns.light_palette("blue", as_cmap=True)
data_report.style.background_gradient(cmap=cm)

In [ ]:
# confusion matrix
nbm_predictions=nbm.predict(tvec.transform(X_test_cleaned))

cm=confusion_matrix(Y_test,nbm_predictions)
cm

array([[ 154,  864],
       [  16, 5136]])

In [ ]:
# testing the model with sample 'Negative' review
demo_review = np.array(['Defective. Bad. Stopped working after one day use'])
demo_review_X_test = tvec.transform(demo_review)
print(nbm.predict(demo_review_X_test))

# expected output = 0 (Negative)
# actual output = 0 (Negative)

[0]


In [ ]:
# testing the model with sample 'Positive' review
demo_review_2 = np.array(['Good product. highly recommend buying.'])
demo_review_X_test_2 = tvec.transform(demo_review_2)
print(nbm.predict(demo_review_X_test_2))

# expected output = 1 (Positive)
# actual output = 1 (Positive)

[1]
